# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='hash',
        ),
        migrations.AlterField(
            model_name='secret',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 19, 6, 19, 210117)),
        ),
        migrations.AlterField(
            model_name='secret',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
